using Newtonsoft.Json;

namespace SujaySarma.Sdk.Azure.Compute.VirtualMachines
{
    /// <summary>
    /// A single network interface attached to a VM
    /// </summary>
    public class VMNetworkInterface
    {
        /// <summary>
        /// Id of the interface. This is auto-generated by Azure and should never be set!
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; } = string.Empty;

        /// <summary>
        /// Properties
        /// </summary>
        [JsonProperty("properties")]
        public VMNetworkInterfaceProperties Properties { get; set; } = new VMNetworkInterfaceProperties();

        public VMNetworkInterface() { }

        /// <summary>
        /// Instantiate a network interface
        /// </summary>
        /// <param name="isPrimary">Flag indicating if this should be the primary interface (no check are done!)</param>
        public VMNetworkInterface(bool isPrimary)
        {
            Properties = new VMNetworkInterfaceProperties(isPrimary);
        }
    }
}
